# -*- coding: utf-8 -*-
"""QUIZ FINAL (João Paulo, Middian, Eliel, Iohana, Andre Oliveira )

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pEN54jVnmitfQb-_AUOgX7GM_1dHSPf
"""

import random

quiz = [
    ["Qual símbolo é usado para comentários de uma linha em Python?", ["A", "B", "C", "D"], ["//", "#", "/*", "--"], "#"],
    ["Qual função é usada para imprimir texto na tela em Python?", ["A", "B", "C", "D"], ["show()", "display()", "console.log()", "print()"], "print()"],
    ["Qual estrutura de dados em Python é mais semelhante a um array em outras linguagens?", ["A", "B", "C", "D"], ["Tupla ", "Dicionário", "Array", "Set"], "Array"],
    ["Qual palavra-chave é usada para definir uma função em Python?", ["A", "B", "C", "D"], ["function", "def", "func", "define"], "def"],
    ["Qual operador é usado para verificar igualdade em Python?", ["A", "B", "C", "D"], ["=", "===", "==", ".equals()"], "=="]
]

random.shuffle(quiz)

acertos, erros, J, gabarito, respostas = 0, 0, 1, [], []

for pergunta, letras, opcoes, correta in quiz:
    random.shuffle(opcoes)
    print(f"{J}) {pergunta}")


    for i in range(len(opcoes)):
        print(f"{letras[i]}) {opcoes[i]}")
        if opcoes[i] == correta:
          resposta_certa = letras[i]

    respostas.append(correta)
    gabarito.append(resposta_certa)

    resposta = input("Digite a letra da sua resposta: ")

    if (resposta == resposta_certa) or (resposta_certa == "A" and resposta == "a") or (resposta_certa == "B" and resposta == "b") or (resposta_certa == "C" and resposta == "c") or (resposta_certa == "D" and resposta == "d"):
        print("Certo!\n")
        acertos += 1
    else:
        print("Errado!\n")
        erros += 1

    J += 1

print(f"Quantidade de perguntas acertadas {acertos}\nQuantidade de perguntas erradas {erros}\n")

print("Gabarito correto:")
for i in range(len(quiz)):
    print(f"{i+1}) {quiz[i][0]} Resposta: {gabarito[i]}) {respostas[i]}")